### ISSUE TITLE
config path for storageOptions has changed

### ISSUE THREAD

**Issue by PascalPflaum** [patrickhulce/umzug-mongo#1]
Hi.

It looks like the storage was called with the whole umzug config object in the past.
In the current version of umzug the storage ist just called with the "storageOptions" property.

I could workaround with nesting another "storageOptions" in the "storageOptions" property, but maybe you want to change your code to support older versions of umzug and the current one.

If you are interested, I would make those changes and create a pull request.

**Comment by patrickhulce** [comment]
Thanks for the report @PascalPflaum! I'm not actively using this package at the moment, but if you want to make a pull request with the upgrade I'd be happy to accept and publish a new version :)

**Comment by francisbrito** [comment]
I'm also in need of this change. @PascalPflaum should you need any help, I'd be glad to help

**Comment by PascalPflaum** [comment]
Thanks @francisbrito, but I already made the tiny change.

@patrickhulce Please notice #2.

**Comment by patrickhulce** [comment]
published as 1.2 🎉  thanks again guys!
