### ISSUE TITLE
Update Dependency

### ISSUE THREAD

**Issue by PascalPflaum** [patrickhulce/umzug-mongo#3]
I just noticed the warning.

> umzug-mongo@1.1.0 requires a peer of umzug@^1.11.0 but none was installed.

I would like to update the package.json to get rid of the warning, but I'm a little bit short on time today, but I will do the change on the next weekend, if nobody did it before.

**Comment by patrickhulce** [comment]
fixed by #4, nice work!

**Comment by patrickhulce** [comment]
published as 1.2.1 👍
